import Head from 'next/head';
import { trpc } from '../utils/trpc';

export default function Home() {
  const hi = trpc.note.get.useQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {hi.isLoading && <>loading</>}
        {hi.data && <>{hi.data.map((el) => el.text)}</>}
      </main>
    </>
  );
}
