version: '3.8'
services:
  notyappdb:
    container_name: notyappdb
    build:
      context: .
      dockerfile: ./Dockerfile-Mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: noty_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://notyappapi:3306']
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - noty

  notyappapi:
    container_name: notyappapi
    depends_on:
      - notyappdb
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL_DOCKER
    stdin_open: true
    tty: true
    networks:
      - noty
networks:
  noty:
