version: '3.8'
services:
  mysqldb:
    image: mysql
    env_file: ./.env
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    networks:
      - notifie
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
    stdin_open: true
    tty: true

networks:
  notifie:
