version: '3.8'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./Dockerfilemysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: notydb
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - noty

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL_DOCKER
    stdin_open: true
    tty: true
    networks:
      - noty
    depends_on:
      db:
        condition: service_healthy

networks:
  noty:
