version: '3.8'
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: notydb
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'notydb']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - noty

  pgadmin-service:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres-service
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - noty

  notyapi-service:
    container_name: notyapi
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    networks:
      - noty
    depends_on:
      postgres-service:
        condition: service_healthy

networks:
  noty:
