version: '3.8'
services:
  notymysql:
    container_name: notymysql
    build:
      context: .
      dockerfile: ./Dockerfilemysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: primary_database
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - noty

  notyapi:
    container_name: notyapi
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL_DOCKER
    stdin_open: true
    tty: true
    networks:
      - noty
    depends_on:
      notymysql:
        condition: service_healthy

networks:
  noty:
