version: '3.8'
services:
  dev_db:
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: noty_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - noty
  app:
    depends_on:
      - dev_db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
    stdin_open: true
    tty: true
    networks:
      - noty
networks:
  noty:
